# !!! This compose file only for development use
version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=laf-sys
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network

  system-server:
    # image: node:16-alpine
    build: ./packages/system-server
    user: root
    working_dir: /app
    environment:
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      ACCOUNT_DEFAULT_APP_QUOTA: 5
      SERVICE_DRIVER: docker
      APP_SERVICE_IMAGE: lafyun/app-service:latest
      APP_SERVICE_DEPLOY_HOST: local-dev.host:8080 # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      APP_SERVICE_DEPLOY_URL_SCHEMA: 'http'
      APP_SERVICE_ENV_NPM_INSTALL_FLAGS: '--registry=https://registry.npm.taobao.org --no-audit --no-fund'
      STORAGE_SERVICE_API_ENTRYPOINT: http://storage-service:9010
      STORAGE_SERVICE_SECRET: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      STORAGE_SERVICE_DEPLOY_HOST: fs.local-dev.host:8080 # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      MINIO_ACCESS_KEY: minio-root-user
      MINIO_ACCESS_SECRET: minio-root-password
      MINIO_INTERNAL_ENDPOINT: http://oss:9000
      MINIO_EXTERNAL_ENDPOINT: http://oss.local-dev.host:8080
      DEBUG_BIND_HOST_APP_PATH: '${PWD}/packages/app-service'
      INIT_ROOT_ACCOUNT_PASSWORD: abc123
    command: sh /app/start.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./packages/system-server:/app
      - ./packages/database-proxy:/app/node_modules/database-proxy:ro
      - ./packages/database-ql:/app/node_modules/database-ql:ro
      - ./packages/database-ql:/app/node_modules/database-proxy/node_modules/database-ql:ro
    ports:
      - "9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - laf_shared_network

  gateway:
    image: openresty/openresty:latest
    depends_on:
      - mongo
      - system-server
    environment:
      DEPLOY_DOMAIN: "*.local-dev.host" # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      DEPLOY_FS_DOMAIN: "*.fs.local-dev.host"
      DEPLOY_OSS_DOMAIN: "oss.local-dev.host"
      SYS_CLIENT_HOST: console.local-dev.host
      DOCS_HOST: docs.local-dev.host
    volumes:
      - ./packages/gateway/scripts:/scripts
      - ./packages/system-client/dist:/app
      - ./packages/app-console/dist:/app-console
      - ./docs/.vitepress/dist:/docs
      - ./packages/gateway/conf.docker/app.conf:/etc/nginx/templates/app.conf.template
      - ./packages/gateway/conf.docker/system.conf:/etc/nginx/templates/system.conf.template
      - ./packages/gateway/conf.docker/fs-proxy.conf:/etc/nginx/templates/fs-proxy.conf.template
    command: "sh /scripts/start.sh"
    ports:
      - 8080:80
    networks:
      - laf_shared_network

  oss:
    image: 'bitnami/minio:2022.4.12'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=oss/data/{0...3}
      - MINIO_ETCD_ENDPOINTS=http://etcd:2379
      - MINIO_SKIP_CLIENT=yes
    ports:
      - "9020:9000"
      - "9120:9001"
    volumes:
      - oss-data:/data
    networks:
      - laf_shared_network

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      - etcd-data:/bitnami/etcd/data
    ports:
      - 12379:2379
      - 12380:2380
    networks:
      - laf_shared_network
  
  # deprecated: just used for old versions
  storage-service:
    image: lafyun/storage-service:latest
    user: root
    working_dir: /app
    environment:
      DB_URI: mongodb://root:password123@mongo:27017/laf-fs?authSource=admin&replicaSet=laf&writeConcern=majority
      LOG_LEVEL: debug
      SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567

    ports:
      - "9010"
    depends_on:
      - mongo
    tmpfs:
      - /tmp
    restart: always
    networks:
      - laf_shared_network

volumes:
  db-data:
  oss-data:
  etcd-data:

networks:
  laf_shared_network:
    external: true
