version: '3.8'
services: 
  mongo:
    image: bitnami/mongodb:latest
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo
      - MONGODB_REPLICA_SET_NAME=rs0
    volumes:
      - db-data:/data/db
    ports:
      - "27018:27017"

  devops_server:
    image: node:14-alpine
    user: node
    working_dir: /app
    environment: 
      SYS_DB: laf-sys
      SYS_DB_URI: mongodb://mongo:27017
      SYS_DB_POOL_LIMIT: 10
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      SYS_ADMIN: laf-sys
      SYS_ADMIN_PASSWORD: laf-sys
      LOG_LEVEL: debug
      PORT: 9000
      APP_DB: laf-app
      APP_DB_URI: mongodb://mongo:27017
      APP_DB_POOL_LIMIT: 100
      APP_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
    command: sleep 5 && npm run init-start
    volumes:
      - ./packages/devops-server:/app
    ports:
      - "9000:9000"
    read_only: true
    depends_on: 
      - mongo
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always

  app_server:
    image: node:14-alpine
    user: node
    working_dir: /app
    environment: 
      DB: laf-app
      DB_URI: mongodb://mongo:27017
      DB_POOL_LIMIT: 100
      SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      LOG_LEVEL: debug
      PORT: 8000
    command: sleep 5 && npm run start
    volumes:
      - ./packages/app-server:/app
      - app-data:/app/data
    ports:
      - "8000:8000"
    read_only: true
    depends_on: 
      - devops_server
      - mongo
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always

  devops_admin:
    image: nginx:latest
    volumes:
      - ./packages/devops-admin/dist:/app
      - ./packages/devops-admin/nginx.conf:/etc/nginx/conf.d/app.conf
    ports: 
      - 8080:80
      
volumes:
  app-data:
  db-data:
      