# !!! This compose file only for development use
version: '3.8'
services: 
  mongo:
    image: bitnami/mongodb:5.0
    environment: 
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=laf-sys
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks: 
      - laf_shared_network
      
  system_server:
    image: node:16-alpine
    user: root
    working_dir: /app
    environment: 
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      APP_SERVICE_IMAGE: lafyun/app-service:latest
      ACCOUNT_DEFAULT_APP_QUOTA: 5
      APP_SERVICE_DEPLOY_HOST: local-dev.host:8080     # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      APP_SERVICE_DEPLOY_URL_SCHEMA: 'http'
    command: npx nodemon
    volumes:
      - ./packages/system-server:/app
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    ports:
      - "9000"
    read_only: true
    depends_on: 
      - mongo
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always
    networks: 
      - laf_shared_network

  system_client:
    image: nginx:latest
    depends_on: 
      - mongo
      # - system_server
    environment: 
      DEPLOY_DOMAIN: "*.local-dev.host"     # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      SYS_CLIENT_HOST: console.local-dev.host
    volumes:
      - ./packages/system-client/dist:/app
      - ./packages/system-client/nginx.conf:/etc/nginx/templates/default.conf.template
    ports: 
      - 8080:80
    networks: 
      - laf_shared_network
      
volumes:
  db-data:
      
networks:
  laf_shared_network:
    external: true