version: '3.8'
services: 
  mongo:
    image: bitnami/mongodb:latest
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=laf-sys
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks: 
      - laf_shared_network

  system_server:
    image: lafyun/system-server:latest
    user: root
    working_dir: /app
    environment: 
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      APP_SERVICE_IMAGE: lafyun/app-service:latest
    command: dockerize -wait tcp://mongo:27017 node dist/index.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000"
    read_only: true
    depends_on: 
      - mongo
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always
    networks: 
      - laf_shared_network

  system_client:
    image: lafyun/system-client:latest
    depends_on: 
      - system_server
      - mongo
    ports: 
      - 8080:80
    networks: 
      - laf_shared_network

networks:
  laf_shared_network:
    external: true
      
volumes:
  db-data:
      