# !!! This compose file only for development use
version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=laf-sys
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network

  system_server:
    image: node:16-alpine
    user: root
    working_dir: /app
    environment:
      SYS_DB_URI: mongodb://my_user:password123@mongo:27017/?authSource=laf-sys&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:password123@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: debug
      ACCOUNT_DEFAULT_APP_QUOTA: 5
      APP_SERVICE_IMAGE: lafyun/app-service:latest
      APP_SERVICE_DEPLOY_HOST: local-dev.host:8080 # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      APP_SERVICE_DEPLOY_URL_SCHEMA: 'http'
      STORAGE_SERVICE_API_ENTRYPOINT: http://storage_service:9010
      STORAGE_SERVICE_SECRET: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      DEBUG_BIND_HOST_APP_PATH: '${PWD}/packages/app-service'
    command: npx nodemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./packages/system-server:/app
      - ./packages/cloud-function:/app/node_modules/cloud-function-engine:ro
      - ./packages/database-proxy:/app/node_modules/database-proxy:ro
      - ./packages/database-ql:/app/node_modules/database-ql:ro
      - ./packages/database-ql:/app/node_modules/database-proxy/node_modules/database-ql:ro
    ports:
      - "9000"
    depends_on:
      - mongo
    restart: always
    networks:
      - laf_shared_network

  gateway:
    image: openresty/openresty:latest
    depends_on:
      - mongo
      - system_server
    environment:
      DEPLOY_DOMAIN: "*.local-dev.host" # `*.local-dev.host` always resolved to 127.0.0.1, used to local development
      SYS_CLIENT_HOST: console.local-dev.host
    volumes:
      - ./packages/gateway/scripts:/scripts
      - ./packages/system-client/dist:/app
      - ./packages/gateway/app.conf:/etc/nginx/templates/app.conf.template
      - ./packages/gateway/system.conf:/etc/nginx/templates/system.conf.template
    command: "sh /scripts/start.sh"
    ports:
      - 8080:80
    networks:
      - laf_shared_network

  storage_service:
    image: node:16-alpine
    user: root
    working_dir: /app
    environment:
      DB_URI: mongodb://root:password123@mongo:27017/laf-fs?authSource=admin&replicaSet=laf&writeConcern=majority
      LOG_LEVEL: debug
      SERVER_SECRET_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
    command: npx nodemon
    volumes:
      - ./packages/storage-service:/app
    ports:
      - "9010"
    depends_on:
      - mongo
    tmpfs:
      - /tmp
    restart: always
    networks:
      - laf_shared_network

volumes:
  db-data: null
  grifs-data:

    null
networks:
  laf_shared_network:
    external: true
