blank_issues_enabled: false
contact_links:
  - name: Contact US
    url: https://docs.qq.com/form/page/DS0tCWXpQc2NpR3dR
    about: Please contact us.
  - name: Business Inquiries
    url: https://docs.qq.com/form/page/DS0tCWXpQc2NpR3dR
    about: Please contact us.