version: '3.8'
services: 
  mongo:
    image: bitnami/mongodb:latest
    environment: 
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_INITIAL_PRIMARY_HOST=mongo
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${SYS_DB}
      - MONGODB_USERNAME=${SYS_DB_USER}
      - MONGODB_PASSWORD=${SYS_DB_PASSWORD}
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks: 
      - laf_shared_network

  system_server:
    image: lafyun/system-server:latest
    user: root
    working_dir: /app
    environment: 
      SYS_DB_URI: mongodb://${SYS_DB_USER}:${SYS_DB_PASSWORD}@mongo:27017/?authSource=${SYS_DB}&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:${MONGODB_ROOT_PASSWORD}@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: ${SYS_SERVER_SECRET_SALT}
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      APP_SERVICE_IMAGE: ${APP_SERVICE_IMAGE:-lafyun/app-service:latest}
      ACCOUNT_DEFAULT_APP_QUOTA: ${ACCOUNT_DEFAULT_APP_QUOTA:-2}
      APP_SERVICE_DEPLOY_HOST: ${DEPLOY_DOMAIN:?err}:${PUBLISH_PORT:-8080}
    command: dockerize -wait tcp://mongo:27017 node dist/index.js
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
    depends_on: 
      - mongo
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always
    networks: 
      - laf_shared_network

  system_client:
    image: lafyun/system-client:latest
    depends_on: 
      - system_server
      - mongo
    environment: 
       DEPLOY_DOMAIN: ${DEPLOY_DOMAIN:?err}
       SYS_CLIENT_HOST: console.${DEPLOY_DOMAIN:?err}
    ports: 
      - ${PUBLISH_PORT:-8080}:80
    networks: 
      - laf_shared_network

networks:
  laf_shared_network:
    external: true
      
volumes:
  db-data: