---
kind: Service
apiVersion: v1
metadata:
  name: storage-service
  namespace: laf
spec:
  selector:
    app: storage-service
  type: ClusterIP
  ports:
    - port: 9010
      targetPort: 9010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: laf
  labels:
    app: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      automountServiceAccountToken: false
      containers:
        - image: lafyun/storage-service:0.7.0
          name: storage-service
          resources:
            # requests:
            #   memory: "128Mi"
            #   cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DB_URI
              value: mongodb://root:password123@mongo:27017/laf-fs?authSource=admin&replicaSet=laf&writeConcern=majority
            - name: LOG_LEVEL
              value: debug
            - name: SERVER_SECRET_SALT
              value: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
          ports:
            - containerPort: 9010
          command: ["node", "/app/dist/index.js"]
          volumeMounts:
            - name: local-storage-service
              mountPath: /app
      restartPolicy: Always
      volumes:
        - name: local-storage-service
          hostPath:
            path: /Users/fugen/codes/less/laf/packages/storage-service
