---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: laf
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gateway
  namespace: laf
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      automountServiceAccountToken: false
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
        - image: lafyun/gateway:0.7.4
          name: gateway
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: DEPLOY_DOMAIN
              value: "*.local-dev.host"
            - name: DEPLOY_FS_DOMAIN
              value: "*.fs.local-dev.host"
            - name: SYS_CLIENT_HOST
              value: console.local-dev.host
            - name: DOCS_HOST
              value: docs.local-dev.host
            - name: SERVICE_DRIVER
              value: kubernetes
          ports:
            - containerPort: 80
      restartPolicy: Always
