version: '3.8'
services: 
  sys_server:
    build: .
    image: laf-sys-server:latest
    environment: 
      SERVER_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      DB: laf_sys_db
      DB_URI: mongodb://mongodb:27017
      DB_POOL_LIMIT: 100
      SUPER_ADMIN: less
      SUPER_ADMIN_PASSWORD: less123
      LOG_LEVEL: debug
    command: npm run init-start
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    networks: 
      - lsf

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks: 
      - lsf

networks:
  lsf:
      
volumes:
  db-data:
      