version: '3.8'
services: 
  server:
    image: lessx/less-framework:latest
    user: node
    environment: 
      SERVER_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      DB: less_app
      DB_URI: mongodb://less:less123@mongodb:27017
      DB_POOL_LIMIT: 100
      SUPER_ADMIN: less
      SUPER_ADMIN_PASSWORD: less123
      LOG_LEVEL: debug
    command: npm run init-start
    volumes:
      - app-data:/app/data
    ports:
      - "8000:8000"
    read_only: true
    cap_drop: 
      - ALL
    tmpfs: 
      - /tmp
    restart: always
    networks: 
      - laf

  mongodb:
    image: mongo:latest
    user: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: less
      MONGO_INITDB_ROOT_PASSWORD: less123
    volumes:
      - db-data:/data/db
    networks: 
      - laf

  admin:
    image: lessx/less-admin:latest
    ports: 
      - 8080:80
    networks: 
      - laf

networks:
  laf:
      
volumes:
  app-data:
  db-data:
      