version: '3'
services: 
  app:
    build: .
    image: less-framework:latest
    environment: 
      SERVER_SALT: Rewrite_Your_Own_Secret_Salt_abcdefg1234567
      DB: less_app
      DB_URI: mongodb://mongodb:27017
      DB_POOL_LIMIT: 100
      SUPER_ADMIN: less
      SUPER_ADMIN_PASSWORD: less123
      LOG_LEVEL: debug
    command: npm run init-start
    volumes:
      - .:/app
      - app-data:/app/data
    ports:
      - "8080:8080"
    networks: 
      - less

  mongodb:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks: 
      - less

networks:
  less:
      
volumes:
  app-data:
  db-data:
      