---
kind: Service
apiVersion: v1
metadata:
  name: system-server
  namespace: laf
spec:
  selector:
    app: system-server
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-server
  namespace: laf
  labels:
    app: system-server
    type: sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: system-server
        type: sys
    spec:
      automountServiceAccountToken: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - image: docker.io/lafyun/system-server:0.7.2
          imagePullPolicy: IfNotPresent
          name: system-server
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 9000
            initialDelaySeconds: 90
            timeoutSeconds: 10
          command: ["sh", "/app/start.sh"]
          env:
            - name: SYS_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: sys-db-uri
            - name: APP_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: app-db-uri
            - name: SYS_SERVER_SECRET_SALT
              valueFrom:
                configMapKeyRef:
                  name: secret-salt
                  key: system-server-salt
            - name: APP_SERVICE_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: app-service
                  key: image
            - name: SERVICE_DRIVER
              value: kubernetes
            - name: APP_SERVICE_MEMORY_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: app-service
                  key: default-memory-limit
            - name: APP_SERVICE_CPU_SHARES
              valueFrom:
                configMapKeyRef:
                  name: app-service
                  key: default-cpu-limit
            - name: ACCOUNT_DEFAULT_APP_QUOTA
              valueFrom:
                configMapKeyRef:
                  name: app-service
                  key: default-app-quota-created-per-user
            - name: APP_SERVICE_DEPLOY_HOST
              valueFrom:
                configMapKeyRef:
                  name: deploy-domain
                  key: app-service-host
            - name: APP_SERVICE_DEPLOY_URL_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: deploy-domain
                  key: deploy-url-schema
            - name: STORAGE_SERVICE_SECRET
              valueFrom:
                configMapKeyRef:
                  name: secret-salt
                  key: system-server-salt
            - name: STORAGE_SERVICE_DEPLOY_HOST
              valueFrom:
                configMapKeyRef:
                  name: deploy-domain
                  key: fs-service-host
            - name: INIT_ROOT_ACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: root-account
                  key: account
            - name: INIT_ROOT_ACCOUNT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: root-account
                  key: password
            - name: STORAGE_SERVICE_API_ENTRYPOINT
              value: http://storage-service:9010
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 9000
