---
kind: Service
apiVersion: v1
metadata:
  name: storage-service
  namespace: laf
spec:
  selector:
    app: storage-service
  type: ClusterIP
  ports:
    - port: 9010
      targetPort: 9010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  namespace: laf
  labels:
    app: storage-service
    type: sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: storage-service
        type: sys
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - image: docker.io/lafyun/storage-service:0.7.6
          imagePullPolicy: IfNotPresent
          name: storage-service
          startupProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: fs-db-uri
            - name: SERVER_SECRET_SALT
              valueFrom:
                configMapKeyRef:
                  name: secret-salt
                  key: fs-server-salt
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 9010
          command: ["node", "/app/dist/index.js"]
