---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: laf
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: laf
  labels:
    app: gateway
    type: sys
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        type: sys
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      containers:
        - image: docker.io/lafyun/gateway:0.7.7
          imagePullPolicy: IfNotPresent
          name: gateway
          startupProbe:
            httpGet:
              path: /gw-health
              port: http
              httpHeaders:
                - name: Referer
                  value: startupProbe
            periodSeconds: 3
            timeoutSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /gw-health
              port: http
              httpHeaders:
                - name: Referer
                  value: readinessProbe
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: SERVICE_DRIVER
              value: kubernetes
          ports:
            - containerPort: 80
              name: http
