version: '3.8'
services:
  mongo:
    image: bitnami/mongodb:5.0
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${SYS_DB}
      - MONGODB_USERNAME=${SYS_DB_USER}
      - MONGODB_PASSWORD=${SYS_DB_PASSWORD}
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network

  system-server:
    image: lafyun/system-server:latest
    user: root
    working_dir: /app
    environment:
      SYS_DB_URI: mongodb://${SYS_DB_USER}:${SYS_DB_PASSWORD}@mongo:27017/?authSource=${SYS_DB}&replicaSet=laf&writeConcern=majority
      APP_DB_URI: mongodb://root:${MONGODB_ROOT_PASSWORD}@mongo:27017/?authSource=admin&replicaSet=laf&writeConcern=majority
      SYS_SERVER_SECRET_SALT: ${SYS_SERVER_SECRET_SALT}
      SHARED_NETWORK: laf_shared_network
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      APP_SERVICE_IMAGE: ${APP_SERVICE_IMAGE:-lafyun/app-service:latest}
      ACCOUNT_DEFAULT_APP_QUOTA: ${ACCOUNT_DEFAULT_APP_QUOTA:-2}
      APP_SERVICE_DEPLOY_HOST: ${DEPLOY_DOMAIN:?err}:${PUBLISH_PORT:-8080}
      APP_SERVICE_DEPLOY_URL_SCHEMA: ${APP_SERVICE_DEPLOY_URL_SCHEMA}
      STORAGE_SERVICE_API_ENTRYPOINT: http://storage_service:9010
      STORAGE_SERVICE_SECRET: ${SYS_SERVER_SECRET_SALT}
      STORAGE_SERVICE_DEPLOY_HOST: "fs.${DEPLOY_DOMAIN:?err}:${PUBLISH_PORT:-8080}"
      INIT_ROOT_ACCOUNT: ${INIT_ROOT_ACCOUNT}
      INIT_ROOT_ACCOUNT_PASSWORD: ${INIT_ROOT_ACCOUNT_PASSWORD:?err}
    command: dockerize -wait tcp://mongo:27017 sh start.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
    depends_on:
      - mongo
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    restart: always
    networks:
      - laf_shared_network

  gateway:
    image: lafyun/gateway:latest
    depends_on:
      - system_server
      - mongo
    environment:
      DEPLOY_DOMAIN: "*.${DEPLOY_DOMAIN:?err}"
      DEPLOY_FS_DOMAIN: "*.fs.${DEPLOY_DOMAIN:?err}"
      SYS_CLIENT_HOST: ${SYS_CLIENT_HOST:?err}
      DOCS_HOST: "docs.${DEPLOY_DOMAIN:?err}"
    command: "sh /scripts/start.sh"
    ports:
      - ${PUBLISH_PORT:-8080}:80
    networks:
      - laf_shared_network

  storage-service:
    image: lafyun/storage-service:latest
    user: root
    working_dir: /app
    environment:
      DB_URI: mongodb://root:${MONGODB_ROOT_PASSWORD}@mongo:27017/laf_fs?authSource=admin&replicaSet=laf&writeConcern=majority
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      SERVER_SECRET_SALT: ${SYS_SERVER_SECRET_SALT}
    command: dockerize -wait tcp://mongo:27017 node dist/index.js
    ports:
      - "9010"
    depends_on:
      - mongo
    tmpfs:
      - /tmp
    restart: always
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  db-data: null
